import {
    FaChartPie,
    FaBook,
    FaUserPen,
    FaTags,
    FaBoxesStacked,
    FaCalendarCheck,
    FaCartShopping,
    FaClockRotateLeft,
    FaChartColumn,
    FaUsers,
    FaUserGroup,
    FaTruckFast,
    FaCreditCard,
    FaReceipt,
    FaGear,
} from 'react-icons/fa6';

export const navPrincipal = [
    { nombre: 'Resumen', ruta: '/dashboard', icono: FaChartPie, descripcion: 'Resumen general del sistema', seccion: 'General' },
    { nombre: 'Libros', ruta: '/libros', icono: FaBook, descripcion: 'Gestión de libros', seccion: 'Catálogo' },
    { nombre: 'Autores', ruta: '/autores', icono: FaUserPen, descripcion: 'Gestión de autores', seccion: 'Catálogo' },
    { nombre: 'Categorías', ruta: '/categorias', icono: FaTags, descripcion: 'Gestión de categorías', seccion: 'Catálogo' },
    { nombre: 'Inventario', ruta: '/inventario', icono: FaBoxesStacked, descripcion: 'Stock y ubicaciones', seccion: 'Catálogo' },
    { nombre: 'Reservas', ruta: '/reservas', icono: FaCalendarCheck, descripcion: 'Gestión de reservas', seccion: 'Operaciones' },
    { nombre: 'Ventas', ruta: '/ventas', icono: FaCartShopping, descripcion: 'Compras: quién compró, qué y cuánto', seccion: 'Operaciones' },
    { nombre: 'Comprobantes', ruta: '/comprobantes', icono: FaReceipt, descripcion: 'Boletas y facturas emitidas', seccion: 'Operaciones' },
    { nombre: 'Pagos', ruta: '/pagos', icono: FaCreditCard, descripcion: 'Pagos recibidos de las ventas', seccion: 'Operaciones' },
    { nombre: 'Usuarios', ruta: '/usuarios', icono: FaUsers, descripcion: 'Control de usuarios registrados', seccion: 'Administración' },
    { nombre: 'Clientes', ruta: '/clientes', icono: FaUserGroup, descripcion: 'Clientes y su actividad de compras', seccion: 'Administración' },
    { nombre: 'Agencias', ruta: '/agencias', icono: FaTruckFast, descripcion: 'Agencias de envío courier', seccion: 'Administración' },
    { nombre: 'Historial', ruta: '/historial', icono: FaClockRotateLeft, descripcion: 'Auditoría de operaciones', seccion: 'Control' },
    { nombre: 'Reportes', ruta: '/reportes', icono: FaChartColumn, descripcion: 'Estadísticas y reportes', seccion: 'Control' },
    { nombre: 'Datos de la empresa', ruta: '/configuracion/empresa', icono: FaGear, descripcion: 'Configuración del emisor de comprobantes', seccion: 'Control' },
];
