import {
    FaChartPie,
    FaBook,
    FaUserPen,
    FaTags,
    FaBoxesStacked,
    FaCalendarCheck,
    FaCartShopping,
    FaClockRotateLeft,
    FaChartColumn,
    FaUsers,
    FaUserGroup,
    FaTruckFast,
    FaCreditCard,
    FaReceipt,
    FaGear,
} from 'react-icons/fa6';

export const navPrincipal = [
    { nombre: 'Dashboard', ruta: '/dashboard', icono: FaChartPie, descripcion: 'Resumen general del sistema' },
    { nombre: 'Libros', ruta: '/libros', icono: FaBook, descripcion: 'Gestión de libros' },
    { nombre: 'Autores', ruta: '/autores', icono: FaUserPen, descripcion: 'Gestión de autores' },
    { nombre: 'Categorías', ruta: '/categorias', icono: FaTags, descripcion: 'Gestión de categorías' },
    { nombre: 'Inventario', ruta: '/inventario', icono: FaBoxesStacked, descripcion: 'Stock y ubicaciones' },
    { nombre: 'Reservas', ruta: '/reservas', icono: FaCalendarCheck, descripcion: 'Gestión de reservas' },
    { nombre: 'Ventas', ruta: '/ventas', icono: FaCartShopping, descripcion: 'Compras: quién compró, qué y cuánto' },
    { nombre: 'Comprobantes', ruta: '/comprobantes', icono: FaReceipt, descripcion: 'Boletas y facturas emitidas' },
    { nombre: 'Pagos', ruta: '/pagos', icono: FaCreditCard, descripcion: 'Pagos recibidos de las ventas' },
    { nombre: 'Usuarios', ruta: '/usuarios', icono: FaUsers, descripcion: 'Control de usuarios registrados' },
    { nombre: 'Clientes', ruta: '/clientes', icono: FaUserGroup, descripcion: 'Clientes y su actividad de compras' },
    { nombre: 'Agencias', ruta: '/agencias', icono: FaTruckFast, descripcion: 'Agencias de envío courier' },
    { nombre: 'Historial', ruta: '/historial', icono: FaClockRotateLeft, descripcion: 'Auditoría de operaciones' },
    { nombre: 'Reportes', ruta: '/reportes', icono: FaChartColumn, descripcion: 'Estadísticas y reportes' },
    { nombre: 'Datos de la empresa', ruta: '/configuracion/empresa', icono: FaGear, descripcion: 'Configuración del emisor de comprobantes' },
];
