import {
    LayoutDashboard,
    BookOpen,
    PenTool,
    Tags,
    Boxes,
    CalendarCheck,
    ShoppingCart,
    ReceiptText,
    CreditCard,
    Users,
    UserRound,
    Building2,
    History,
    Settings,
} from 'lucide-react';

export const navPrincipal = [
    { nombre: 'Resumen', ruta: '/dashboard', icono: LayoutDashboard, descripcion: 'Resumen general, estadísticas y reportes', seccion: 'General' },
    { nombre: 'Libros', ruta: '/libros', icono: BookOpen, descripcion: 'Gestión de libros', seccion: 'Catálogo' },
    { nombre: 'Autores', ruta: '/autores', icono: PenTool, descripcion: 'Gestión de autores', seccion: 'Catálogo' },
    { nombre: 'Categorías', ruta: '/categorias', icono: Tags, descripcion: 'Gestión de categorías', seccion: 'Catálogo' },
    { nombre: 'Inventario', ruta: '/inventario', icono: Boxes, descripcion: 'Stock y ubicaciones', seccion: 'Catálogo' },
    { nombre: 'Reservas', ruta: '/reservas', icono: CalendarCheck, descripcion: 'Gestión de reservas', seccion: 'Operaciones' },
    { nombre: 'Ventas', ruta: '/ventas', icono: ShoppingCart, descripcion: 'Compras: quién compró, qué y cuánto', seccion: 'Operaciones' },
    { nombre: 'Comprobantes', ruta: '/comprobantes', icono: ReceiptText, descripcion: 'Boletas y facturas emitidas', seccion: 'Operaciones' },
    { nombre: 'Pagos', ruta: '/pagos', icono: CreditCard, descripcion: 'Pagos recibidos de las ventas', seccion: 'Operaciones' },
    { nombre: 'Usuarios', ruta: '/usuarios', icono: Users, descripcion: 'Control de usuarios registrados', seccion: 'Administración' },
    { nombre: 'Clientes', ruta: '/clientes', icono: UserRound, descripcion: 'Clientes y su actividad de compras', seccion: 'Administración' },
    { nombre: 'Agencias', ruta: '/agencias', icono: Building2, descripcion: 'Agencias de envío courier', seccion: 'Administración' },
    { nombre: 'Historial', ruta: '/historial', icono: History, descripcion: 'Auditoría de operaciones', seccion: 'Control' },
    { nombre: 'Datos de la empresa', ruta: '/configuracion/empresa', icono: Settings, descripcion: 'Configuración del emisor de comprobantes', seccion: 'Control' },
];
